default:
  name: fuse-utils
  version: "1.0.0"
  authors:
    - "Shashanka Prajapati"
  python: 3.7
  dev: false
  PORT: 8080
  DB_NAME: mydb.db
  database:
    host: localhost
    user: default
  plugins:
    - core
  scripts:
    - install.sh
    - deploy.sh

development:
  dev: true
  database:
    user: dev_user
    dynaconf_merge: true
  plugins:
    - debug_toolbar
    - dynaconf_merge
  scripts:
    - dev.sh
    - test.sh
    - deploy.sh
    - dynaconf_merge_unique
  DB_PATH: "@jinja {{env.HOME}}/{{this.current_env | lower}}/{{this.DB_NAME}}"

production:
  database:
    dynaconf_merge:
      user: prod_user
