name: Documentation

on:
    push:
        branches:
            - master
            - dev-git-actions
    pull_request:
        branches:
            - master

jobs:
    document:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2

            - name: Set up Python
              uses: actions/setup-python@v2
              with:
                  python-version: "3.x"

            - name: Get full python version
              id: full-python-version
              run: echo ::set-output name=version::$(python -c "import sys; print('-'.join(str(v) for v in sys.version_info[:3]))")

            - name: Install and set up Poetry
              run: |
                  python -m pip install --upgrade pip
                  pip install --upgrade poetry --pre
                  poetry config virtualenvs.in-project true

            - name: Set up cache
              uses: actions/cache@v1
              with:
                  path: .venv
                  key: venv-${{ runner.os }}-${{ steps.full-python-version.outputs.version }}-${{ hashFiles('**/poetry.lock') }}

            - name: Install dependencies
              run: poetry add sphinx sphinx-rtd-theme toml

            - name: Generate Docs
              run: make docs

            - name: Deploy docs to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: docs/_build/html
                  keep_files: true
