name: Documentation

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master

jobs:
    document:
        runs-on: ubuntu-latest

        steps:
            - name: Deploy
              uses: peaceiris/actions-gh-pages@v3
              run: make docs
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: docs/_build/html
                  keep_files: true
