name: Documentation

on:
    push:
        branches:
            - master
            - dev-git-actions
    pull_request:
        branches:
            - master

jobs:
    document:
        runs-on: ubuntu-latest

        steps:
            - name: Check make commands
              run: make

            - name: Generate Docs
              run: make docs

            - name: Deploy docs to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  deploy_key: ${{ secrets.ACTIONS_DEPLOY_KEY }}
                  publish_dir: docs/_build/html
                  keep_files: true
